name: Continuous Integration

on:
  pull_request: ~
  push:
    branches:
    - main
    - dev

jobs:
  forge-tests:
    runs-on: ubuntu-latest
    container: docker://racket/racket:8.3
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Install cvc5 for SMT (Theory of Relations) backend engine
      run: sudo apt-get install -y cvc5
    - name: Install Forge
      run: |
        raco pkg install --auto --no-docs ./forge ./froglet
    - name: Run tests
      run: |
        cd forge/
        chmod +x run-tests.sh
        ./run-tests.sh tests/
