name: Continuous Integration

on:
  pull_request: 
    branches:
    - main
    - dev
  push:
    branches:
    - main
    - dev
    - feat_smt

# Docker images for various Racket versions available on DockerHub 
# as racket/racket:<version>
# (https://github.com/racket/docker)
# We use features that require at least 8.4; try to use latest.

jobs:
  forge-tests:
    runs-on: self-hosted
    
    container: docker://racket/racket:8.13
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Install cvc5 for SMT (Theory of Relations) backend engine
      run: |
        apt-get update 
        apt-get install -y wget unzip
        wget https://github.com/cvc5/cvc5/releases/download/cvc5-1.2.0/cvc5-Linux-x86_64-static.zip
        unzip cvc5-Linux-x86_64-static.zip
        export PATH=$PATH:`pwd`/cvc5-Linux-x86_64-static/bin
        cvc5 --version 
    - name: Install Forge
      run: |
        raco pkg install --auto --no-docs ./forge ./froglet
    - name: Run tests
      run: |
        cd forge/
        chmod +x run-tests.sh
        ./run-tests.sh tests/
